export const ACTUALIZAR = "ACTUALIZAR";
export const ELIMINAR = "ELIMINAR";
export const OBTENER = "OBETENER";
export const OBTENER_LISTA = "OBETENER_LISTA";
export const OBTENER_ACCIONES = "OBTENER_ACCIONES";
export const REGISTRAR = "REGISTRAR";
export const OBTENER_CALENDARIO_LISTA = "OBTENER_CALENDARIO_LISTA";

export const OBTENER_LISTA_PROFESIONES = "OBTENER_LISTA_PROFESIONES"
export const OBTENER_LISTA_PACIENTES = "OBTENER_LISTA_PACIENTES"